spring:
  main:
#    spring开机log
    log-startup-info: on
#    懒加载
    lazy-initialization: true
  application:
    admin:
      # spring 远程管理，目前感觉没有生效呀
      enabled: true
  task:
    execution:
      pool:
        core-size: 8
        max-size: 16
        queue-capacity: 100
        keep-alive: 10s
        allow-core-thread-timeout: true
    scheduling:
      pool:
        size: 2
      thread-name-prefix: "scheduling-"
      shutdown:
        # 允许等待线程池完成已存在的任务
        await-termination: true
        # 设置等待超时时间
        await-termination-period: 120s

