spring:
  main:
#    spring开机log
    log-startup-info: on
#    懒加载
    lazy-initialization: true
  application:
    admin:
      # spring 远程管理，目前感觉没有生效呀
      enabled: true
  task:
    execution:
      pool:
        core-size: 8
        max-size: 16
        queue-capacity: 100
        keep-alive: 10s
        allow-core-thread-timeout: true
    scheduling:
      pool:
        size: 2
      thread-name-prefix: "scheduling-"
      shutdown:
        # 允许等待线程池完成已存在的任务
        await-termination: true
        # 设置等待超时时间
        await-termination-period: 120s
  # 关闭超时时间
  lifecycle:
    timeout-per-shutdown-phase: 60s

  datasource:
    local:
      url: jdbc:postgresql://localhost:5432/postgres
      platform: postgres
      username: postgres
      password: 921115
    remote:
      url: jdbc:postgresql://localhost:5433/postgres
      platform: postgres
      username: postgres
      password: 921115

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      pool-name: vergilPool
      max-lifetime: 28740000
      connection-test-query: SELECT 1


server:
  # 延时关机，等待网络请求处理完毕
  shutdown: graceful

